## Aim:
How to link the rule-based extracted CI_TYPE-GEO pairs with the respective Ci failure impacts

**Idea**\
Test using prompt engineering by passing table of CIGEO pairs to GPT-J model.
Steps:
* Load model and apply it always on one chunk of the document to extract CI failure impacts 
* Use prompt engineering to extract time and location of the CI failure (origin) the CI impacts (impact location)
or 
* Pass dataframe of pairs as input to the model
or
* Use few shot prompting with example answers

**Finally:**
* Compaire all approaches of spatial and temporal linking CI failure impacts

In [9]:
# %env CUDA_DEVICE_ORDER=PCI_BUS_ID
# %env CUDA_VISIBLE_DEVICES=0  # nvidia gpu
# %env PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# # %env TORCH_CUDA_ARCH_LIST=8.6

# # settings for distributed computing
# %env WORLD_SIZE=1
# %env RANK=0
# %env LOCAL_RANK=0

# # NOTE: # WORLD_SIZE: each GPU corresponds to one process (world = no. of processes within a group), processes communicate with each other enabling eg., distributed training
# # NOTE: # RANK: IDs of the processes, ranging from 0 up to WORLD_SIZE - 1
!sacct

In [2]:
import os
import sys
import subprocess
import re
import time
from glob import glob
from pathlib import Path

from io import StringIO

import numpy as np
import pandas as pd
from jinja2 import Environment, FileSystemLoader
from langchain_docling import DoclingLoader
import spacy
from huggingface_hub import login
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
import torch

from pdfminer.high_level import extract_text
from docling.backend.pypdfium2_backend import PyPdfiumDocumentBackend
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import (
    PdfPipelineOptions,
    AcceleratorOptions,
    AcceleratorDevice,
)
from docling.pipeline.standard_pdf_pipeline import StandardPdfPipeline
from docling.document_converter import DocumentConverter, FormatOption


sys.path.append("./")
from src.settings import settings as s
import src.document_cleaning as dc
from src.hf_model_access import get_weight_dir


torch.manual_seed(42)


#  automatic linebreaks and multi-line cells.
pd.set_option("display.max_colwidth", None)
pd.set_option("display.colheader_justify", "left")

gpu001
Running on TUB Cluster

## Set paths and vars

In [43]:
# os.environ["HF_HOME"] = s.HF_HOME_DIR
login(token=os.getenv("HUGGINGFACE_TOKEN"))

test_mode = False # for testing purposes, limit number of processed documents

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [13]:
DOCS_DIR = "./" + s.PATH_DATA + "text_sources/"
PARSED_TEXT_DIR = "./" + s.PATH_DATA + "parsed_documents/"
LLM_OUTPUTS_DIR = "./" + s.PATH_DATA + "llm_outputs/"
s.NER_PATTERNS_FILEPATH = Path("./" + "ner_patterns.jsonl")

# document cleaning
md_dir = Path(PARSED_TEXT_DIR)
md_dir.mkdir(parents=True, exist_ok=True)

# CI GEO pairs
filename_ci_geo_entities = "extracted_ci_geo_entities.csv"
OUTPUT_CI_GEOFILEPATH = Path("./" + s.PATH_DATA + filename_ci_geo_entities)

## store LLM 1 output 
os.makedirs(LLM_OUTPUTS_DIR, exist_ok=True)
OUTPUT_LMM1_FILENAME = "llm_1_test_eval.csv"
OUTPUT_LLM1_FILEPATH =  Path(LLM_OUTPUTS_DIR +  OUTPUT_LMM1_FILENAME)

## store prompt message
OUTPUT_PROMPT_FILENAME = f"prompt_{OUTPUT_LLM1_FILEPATH.stem}.txt"
OUTPUT_PROMPT_FILEPATH = Path(LLM_OUTPUTS_DIR + OUTPUT_PROMPT_FILENAME )

In [5]:
# # spaCy language model for NER and ENTITY LINKING

print("Try loading spaCy language model for remote machine")
try: 
    nlp = spacy.load(s.SPACY_MODEL)
except (OSError, ValueError):
    try: 
        print(f"spaCy language model '{s.SPACY_MODEL}' not found. Downloading ...")
        subprocess.check_call(["uv", "pip", "install", "spacy-transformers"])
        subprocess.check_call(["uv", "run", "python3", "-m", "spacy", "download", s.SPACY_MODEL])
        nlp = spacy.load(s.SPACY_MODEL)
    except ValueError:
        print("Try downloading directly via python3 -m spacy ... (and not via uv run ...)")
        subprocess.check_call(["python3", "-m", "spacy", "download", s.SPACY_MODEL])

Try loading spaCy language model for remote machine

In [6]:
# %%
# %env MASTER_ADDR=127.0.0.1
# %env MASTER_PORT=6006

# # # Initialize distributed computing
# rank = int(os.environ["RANK"])
# device = torch.device(f"cuda:{rank}")
# torch.cuda.set_device(device)
# torch.distributed.init_process_group(backend="nccl")

# %%
pd.set_option(
    "display.max_colwidth", None
)  #  automatic linebreaks and multi-line cells.
pd.set_option("display.colheader_justify", "left")

## Document cleaning

In [7]:

# %%
# Docling pipeline configs
accelerator_options = AcceleratorOptions(
    num_threads=4, device=AcceleratorDevice.AUTO
)  # use GPU + multi-threading
pipeline_options = PdfPipelineOptions()
pipeline_options.do_ocr = True
pipeline_options.do_table_structure = (
    True  # identify tables as such just not to have them in the TextItems later
)
pipeline_options.accelerator_options = accelerator_options
pipeline_options.force_backend_text = True



# %%
# setup converter for PDF and markdown
converted = DocumentConverter(
    allowed_formats=[InputFormat.PDF, InputFormat.MD],
    format_options={
        InputFormat.PDF: FormatOption(
            pipeline_cls=StandardPdfPipeline,
            pipeline_options=pipeline_options,
            backend=PyPdfiumDocumentBackend,
        ),
    },
)

In [8]:

print( "Number of documents to process:", len(os.listdir(DOCS_DIR)) )


# convert the different layouts of the pdf files into unified markdown format incl. sub/section titles, tables, caption text etc
for pdf_filename in os.listdir(DOCS_DIR):
    if pdf_filename.endswith(".pdf"):

        md_filename = f"{Path(pdf_filename).stem}.md"

        pdf_filepath = os.path.join(DOCS_DIR, Path(pdf_filename))
        md_filepath = os.path.join(PARSED_TEXT_DIR, Path(md_filename))
        cleaned_md_filepath = md_filepath.replace(".md", "_cleaned.md")

        if os.path.exists(md_filepath):
            print(
                f"Markdown file '{md_filepath}' already exists. Skipping conversion and cleaning."
            )
            continue

        start_time = time.time()
        print(f"\nFetching: {pdf_filename}")

        print("Remove reference section")
        pdf_text = extract_text(pdf_filepath)
        pdf_text_no_refs = dc.remove_references(pdf_text)

        print("Removing URLs") # LangExtract tries to open these URLs when they occur in the document text
        pdf_text_no_refs_urls = re.sub(r"http\S+", "", pdf_text_no_refs) 

        # FIXME remove workaround of saving pdf as markdown and reading it again as Docling.Document
        # FIXME with DocLoader
        # loader = DoclingLoader(md_filepath)
        # md_text = loader.load()
        with open(md_filepath, "w", encoding="utf-8") as f:
            f.write(pdf_text_no_refs_urls)
        print("Converting Markdown to text...")
        md_text = converted.convert(md_filepath)

        print("Removing headers and footers\n")
        md_text_cleaned = dc.remove_headers_footers(md_text)

        print(f"Saving parsed and cleaned document as markdown to: {cleaned_md_filepath}")
        md_text_cleaned.document.save_as_markdown(cleaned_md_filepath)

        end_time = time.time() - start_time
        print(f"Parsing and cleaning done. Time elapsed: {end_time:.2f} seconds.")


# visual check of removed items
# TODO make as document_cleaning function: print removed items with largest number of chars first
# ## NOTE. high number of chars == more potentially actual text body

# text_items_removed = sorted(text_items_to_drop_visualization, key=lambda x: -x[0])
# for i in text_items_removed[:50]:
#     print(i) # -->  also subsection titles were removed partly

# %%

Number of documents to process: 46
Markdown file './../data/parsed_documents/Ferlita 2023 - Incendi in Sicilia, ecco cosa accade.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/The Vibes 2022 - Valencia Airport in Madrid briefly shut as lightning hits runway _ World .md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Skoulding 2023 - Where are the fires in Italy today as temperatures rise to 47.6C on Sicily_ _ The Independent.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/AFP 2022 - The_Vibes_Valencia Airport in Madrid briefly shut as lightning hits runway _ World _ The Vibes.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/The Maritime Executive 2024 - A Week After Devastating Floods, Spain’s Valencia Port is Restoring Service.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Lloyd's List 2024 - Port of Valencia reopens after devastating floods.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Brown 2010 - Economy feels chill as UK grinds to a halt _ The Independent.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/The Guardian 2018 - Freezing weather costs UK economy £1bn a day _ UK weather.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Kaur 2025 - Authorities suspect arson in 17 wildfires across Dalmatian coast, Croatia - The Watchers.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Keller and Atzl - 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Containerlift 2024 - Valencia Port Resumes Operations Following Devastating Flooding in Spain - Containerlift.co.uk - Transport_Lifting_Shipping.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Euronews 2024 - Spain floods_ Death toll rises to 205 as nation braces for more rain .md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Wildhagen 2013 - Hochwasser_ Wie die Flut Unternehmen lahmlegt.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Wilson 2024 - Flash floods in Spain sweep away cars, disrupt trains and leave several missing _ AP News.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/European Investment Bank 2025 - Spain_ EIB lends €50 million to Iberdrola to rebuild and climate-proof flood-hit power infrastructure in Valencia.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Stamataki 2023 - Greece’s record rainfall and flash floods are part of a trend _ PreventionWeb.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Karakatsani 2023 - Greece economy briefing The economic impact of the recent devastating floods in Greece.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/ABC 2024 - Traffic jams and flight delays due to heavy rain and lightning storm in Malaga.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Gilbody Dickerson 2024 - Spain floods_ At least 95 people killed including British man near Malaga _ World News _ Sky News.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/EFE 2024 - The DANA storm, live_ The death toll rises to 158.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Plag 2014 - Foreword extreme geohazards—a growing threat for a globally interconnected civilization.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Koks et al 2022 - Brief communication.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Korzilius 2021 -  Nach der Flut  Rheinisches Ärzteblatt 10 -  p12–16.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Korzilius 2021 Nach der Flut.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/UNEP 2013 - Impacts of summer 2003.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Artemis 2015 - PERILS finalises Storm Desmond UK flood loss estimate at £604m.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Treanor 2015 - Storm Desmond damage across Cumbria estimated at £500m _ Storm Desmond _The Guardian.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/PWC 2015 - Updated estimates on cost of Storm Desmond.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Rozendaal 2021 - Infrabel_ Flood damage to railway track worth tens of millions of euros _ SpoorPro - incomplete.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Eurelectric 2006 - Impacts of Severe Storms on Electric Grids.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/IPCC 2018 - Working Group 2 Cross-chapter case studies.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Kettle 2020 - Storm Xaver over Europe in December 2013 Overview of energy impacts and North Sea events.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Koks 2019 - Understanding Business Disruption and Economic Losses Due to Electricity Failures and Flooding.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Koks 2022 - Brief communication.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Krausmann 2014 - STREST report on lessons learned from recent catastrophic events.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Luiijf 2010 - Empirical findings on Critical Infrastructure Dependencies in Europe.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/McGregor 2007 - The social impacts of heat waves.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Stahl 2016 - Impacts of European drought events: insights from an international database of text-based reports.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Tapsell 2010 - Social vulnerability to natural hazards.md' already exists. Skipping conversion and cleaning.
Markdown file './../data/parsed_documents/Yamashita 2008 - Analysis  control  and economic impact assessment of major blackout events.md' already exists. Skipping conversion and cleaning.

# LLama

###  prompt engineering

In [9]:
question_1 = "Which infrastructure failures are mentioned in the text? Categorize the output by the type of infrastructure, the location, and the type of damage."

env = Environment(loader=FileSystemLoader("./prompt_templates/"))
template = env.get_template("ci_loc_direct_impact.txt")


### Apply LLama on chunks 
* extract CI-GEO pairs (ie. most likely geolocation of each CI_TYPE )
* pass NER table to prompt for evaluating and improving LLM response
* Test approach by applying it on three cleaned documents

In [10]:

# %%
# # empty CUDA cache
import gc
import torch

gc.collect()

torch.cuda.empty_cache()
# print(torch.cuda.memory_summary(device=None, abbreviated=False))

# %%
# init class for decoder and tokenizer

In [47]:


class DecoderModel:
    def __init__(self):
        
        try: 
            login(token=os.getenv("HUGGINGFACE_TOKEN"))   # notebook_login
        except:
            login(token=os.environ.get("HUGGINGFACE_TOKEN"))  # former HF_TOKEN

        model_name = "meta-llama/Llama-3.1-70B-Instruct" 
        # model_name = "meta-llama/Llama-2-7b-chat-hf"  # TODO pass as argument
        print(f"Using model: {model_name}")

        base_dir = s.HF_HOME_DIR  # or use default dir.cache/
        model_dir = base_dir + "/hub"  # + "models--" + model_name.replace("/", "--")
        print(model_dir)

        # quantization config
        # Load model with 4-bit quantization if applicable (use 4-bit integer instead of 32b floats) --> reduce the required VRAM for model application
        # see, https://huggingface.co/docs/transformers/quantization
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
        )

        self.pipeline, self.tokenizer = self.initialize_model(
            model_name, model_dir, bnb_config
        )

    def initialize_model(self, model_name: str, model_dir: str = None, bnb_config=None):
        # Model and Tokenizer initialization
        if not os.path.exists(model_dir):
            print("Model directory not found. Downloading model...")
            os.makedirs(model_dir, exist_ok=True)

            device = transformers.infer_device()
            print(f"Using device: {device}")
            model = AutoModelForCausalLM.from_pretrained(
                model_name,
                dtype="auto",
                attn_implementation="flash_attention_2",  # use with 4-bit quantization,
                # --> flash attention enables to use much larger sequence lengths without running into OOM issues
                quantization_config=bnb_config,
                # max_memory={0: "2GB", 1: "10GB"},  # distribute memory across GPUs
            )
            model.save_pretrained(model_dir)
            tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
            tokenizer.save_pretrained(model_dir)

            print("Downloaded model and tokenizer")

        else:
            print(f"Using locally saved model from {model_dir}")

            print("Loading model from local cache ...")
            model_dirname = get_weight_dir(model_name)  # # searches for model in HF_HOME

            try: 
                model = AutoModelForCausalLM.from_pretrained(
                    model_dirname,
                    cache_dir=model_dir,
                    local_files_only=True,  # tp_plan="auto" # set tensor parallel model (ie. splits model on multiple GPU)
                    # dtype="auto",
                    attn_implementation="flash_attention_2",  # use with 4-bit quantization,
                    # --> flash attention enables to use much larger sequence lengths without running into OOM issues
                    quantization_config=bnb_config,
                    # tp_plan="auto",  # automatically use a tensor parallelism plan based on predefined configuration of the model (i.e. partition model on both GPUs)
                )
                # print("Tensor parallel plan:", model._tp_plan)
                
            # TODO fix loading of flash-attn
            except ImportError as e:
                print("Cant load FlashAttention2", e)
                print("Loading model without FlashAttention2 ...")
                model = AutoModelForCausalLM.from_pretrained(
                    model_dirname,
                    cache_dir=model_dir,
                    # dtype="auto",
                    # quantization_config=bnb_config,
                    # tp_plan="auto",  # automatically use a tensor parallelism plan based on predefined configuration of the model (i.e. partition model on both GPUs)
                )
                # print("Tensor parallel plan:", model._tp_plan)
            tokenizer = AutoTokenizer.from_pretrained(
                model_dirname,
                use_fast=True,
                cache_dir=model_dir,  # use fast Rust-based tokenizer, when possible
            )

        # reduce further memory usage
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = model.to(device)
        model.use_checkpointing = True

        torch.cuda.empty_cache()

        # Pipeline setup for question answering
        pipeline = transformers.pipeline(  # load model locally from wsl .cache\
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=1024, # high max token otherwise output is truncated
            device_map="auto",
        )
        return pipeline, tokenizer


    def generate_response(
        self, question: str, context: list, chunk_id: int
    ):
    
        rendered_prompt = template.render(
            context=context,  # includes also df_ci_geo info
            question=question,
        )

        print(f"Generating response for chunk_id: {chunk_id} ...")

        sequences = self.pipeline(
            rendered_prompt,  # jinja template
            max_new_tokens=1024, # use default to not truncate the LLM response
            do_sample=True,
            num_beams=1,  # select token based on probability distribution over entire model’s vocabulary
            # top_k=10,
            # top_p=0.5,
            temperature=0.2,
            # num_return_sequences=1,
            eos_token_id=self.tokenizer.eos_token_id,
            return_full_text=False,  # allow bullet point answers
        )
        # Extracting and returning the generated text
        return sequences

# %%

:

In [12]:

df_responses = pd.DataFrame(
    columns=[
        "chunk_id",
        "infrastructure_type",
        "damage",
        "location",
        "impacts_to_other_infrastructure_assets"
    ]
)

## init LLM pipeline
decoder_model = DecoderModel()

## init output dataframe
df_responses_all = pd.DataFrame()


## Start CI impact extraction
for i, filename in enumerate(glob(str(Path(PARSED_TEXT_DIR, "*cleaned.md")))):

    no_documents = len(glob(str(Path(PARSED_TEXT_DIR, "*cleaned.md"))))
    filepath = Path(filename)
    filename_stem = filepath.stem


    ## load doc
    loader = DoclingLoader(filepath)  # use chunks from Docling.Loader
    doc = loader.load()

    if test_mode == True:
        doc = doc[:4]  # for testin evaluation approach, iterate over max 3 docs
        if i == 4:
            break

    print(f"\n\n ######## -------- Processing document [{i+1}/{no_documents}]: {filepath.name} -------- ######## \n")

    ## extract authors, publication year and title 
    citation = dc.extract_citation_info(filename_stem)


    print(f"\n ######## -------- Getting geolocation of CI assets -------- ######## \n")
    ## Create New entity for transport infrastructure and apply it on any doc

    ## TODO make as pydantic class with fixed attributes
    df_ci_geo = pd.DataFrame(
        columns=[
            "chunk_id",
            "ci_entity",
            "ci_entity_label",
            "geo_entity",
            "geo_entity_label",
            "token_distance",
        ]
    )

    ## get most likely geolocation for each CI entity based on distance
    for i, chunk in enumerate(doc):
        nlp_chunk = nlp(chunk.page_content)
        all_ents = [ent for ent in nlp_chunk.ents]
        ci_type_ents = [ent for ent in nlp_chunk.ents if ent.label_ in ["CI_TYPE", "FAC"]]
        ci_type_ents_info = [ent for ent in nlp_chunk.ents if ent.label_ in ["CI_TYPE"]]
        fac_ents_info = [ent for ent in nlp_chunk.ents if ent.label_ in ["FAC"]]

        # check if chunk contains CI_TYPE entities
        if len(ci_type_ents) > 0:
            print(f"\nChunk [{i}], No. CI_TYPE and FAC entities: {len(ci_type_ents)}")
            # print(
            #     f"Contains following entities for CI_TYPE: {ci_type_ents_info}, FAC: {fac_ents_info}"
            # )
            # print(f"Chunk text [{i}]:", chunk.page_content)

            # iterate over all entities within chunk
            for ent_idx in range(len(all_ents)):
                # when entity is CI_TYPE or FAC (i.e. buidling, airports, highways) do following ...
                if all_ents[ent_idx].label_ in ["CI_TYPE", "FAC"]:
                    ci_idx = ent_idx

                    ## .. calculate distances between CI_TYPE entity and  all GEO entities in chunk based on index position
                    distance_list = []
                    idx_in_chunk = []
                    try:
                        for ent_idx in range(len(all_ents)):
                            # TODO calc distances between CI_TYPE ~ GEO entities based on word numbers and not entities
                            if all_ents[ent_idx].label_ in ["GPE", "LOC"]:
                                geo_idx = ent_idx
                                dist_ent_pair = np.abs(ci_idx - geo_idx)
                                distance_list.append(dist_ent_pair)
                                idx_in_chunk.append((ent_idx))
                                closest_pair_idx = np.argmin(
                                    distance_list
                                )  # idx of closest GEO entity
                                distance_closest_pair = distance_list[closest_pair_idx]

                        threshold = 5  # max token distance between CI_TYPE and GEO entity
                        if distance_closest_pair > threshold:
                            print(
                                f""" Token distance between CI_TYPE/FAR and next GEO entity is {distance_closest_pair} and thus larger than the allowed distance of {threshold} tokens """
                            )
                            continue
                        else:
                            pass
                            # print(
                            #     f"""  Closest GEO entity to CI_TYPE/FAC entity "{all_ents[ci_idx]}" is "{all_ents[idx_in_chunk[closest_pair_idx]]}" at distance {distance_closest_pair}"""
                            # )

                        ## write as dict entry incl chunk_id, ci_entity, geo_entity, distance
                        result_dict = {
                            "chunk_id": i,
                            "ci_entity": all_ents[ci_idx].text,
                            "ci_entity_label": all_ents[ci_idx].label_,
                            "geo_entity": all_ents[idx_in_chunk[closest_pair_idx]].text,
                            "geo_entity_label": all_ents[
                                idx_in_chunk[closest_pair_idx]
                            ].label_,
                            "token_distance": distance_closest_pair,
                        }
                        df_ci_geo = pd.concat(
                            [df_ci_geo, pd.DataFrame([result_dict])], ignore_index=True
                        )

                    except IndexError:
                        # print("No GEO entities found in this chunk.")
                        continue
                    # print("\nidx_in_chunk, closest pair idx", idx_in_chunk, closest_pair_idx)

                    # spacy.displacy.render(
                    #     nlp_chunk, style="ent",
                    #     options={"ents": ["CI_TYPE", "GPE", "LOC", "FAC"], "colors": {"CI_TYPE": "violet"}}
                    # )

            else:
                print("\nNo CI_TYPE or FAC entities found in this chunk.")
                continue


    print(f"\n  #############  -------- Text-2-Data: {filepath.name} -------- #############  \n")

    ## apply decoder on each chunk
    ## TODO replace iteration by loading entire document and use recursive chunking from langchain
    for j, chunk in enumerate(doc):

        if df_ci_geo.loc[df_ci_geo["chunk_id"] == j].empty:
            continue

        context = [
            {
                "text": chunk.page_content,
                "citation": citation,
                "title": filename_stem, 
                "ci_locations": df_ci_geo.loc[df_ci_geo["chunk_id"] == j],
            },  # TODO use author names or Primary keys from DB later
        ]
        ## apply LLM
        response = decoder_model.generate_response(
            question=question_1, context=context, chunk_id=j
        )

        ## postprocess response
        resp = response[0]["generated_text"].replace("\n", "")
        try:
            resp = (resp.split("]")[0] + "]")  # remove potential text outside of json object
            df_resp = pd.read_json(StringIO(resp))
            df_resp["chunk_id"] = j  # add chunk id as identifier
            df_resp["citation"] = citation  # add citation info
            df_responses = pd.concat([df_responses, df_resp], ignore_index=True)
        except ValueError as e:
            print(f"Cannot add response to output dataframe: {e}, \n{resp}")


    df_responses_all = pd.concat([df_responses_all, df_responses], ignore_index=True)


    # clean up after each document
    gc.collect()
    torch.cuda.empty_cache()

# %%
# r = response[0]["generated_text"].replace("\n", "")
# pd.read_json(StringIO(r))#.to_list()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Using model: meta-llama/Llama-3.1-70B-Instruct
/beegfs/home/users/a/a-buch/_PROJECTS/CI-impacts-information-retrieval/notebooks/huggingface_mirror/hub
Using locally saved model from /beegfs/home/users/a/a-buch/_PROJECTS/CI-impacts-information-retrieval/notebooks/huggingface_mirror/hub
Loading model from local cache ...

/beegfs/home/users/a/a-buch/_PROJECTS/CI-impacts-information-retrieval/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:435: UserWarning:
    Found GPU0 Tesla P100-PCIE-16GB which is of cuda capability 6.0.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)

  queued_call()
/beegfs/home/users/a/a-buch/_PROJECTS/CI-impacts-information-retrieval/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:435: UserWarning:
    Please install PyTorch with a following CUDA
    configurations:  12.6 following instructions at
    https://pytorch.org/get-started/locally/

  queued_call()
/beegfs/home/users/a/a-buch/_PROJECTS/CI-impacts-information-retrieval/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:435: UserWarning:
Tesla P100-PCIE-16GB with CUDA capability sm_60 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
If you want to use the Tesla P100-PCIE-16GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  queued_call()

Cant load FlashAttention2 FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
Loading model without FlashAttention2 ...

Loading checkpoint shards:   0%|          | 0/30 [00:00<?, ?it/s]

:

:

In [ ]:
# Cant load FlashAttention2 FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.

#### response

In [ ]:
safety_df = df_responses_all.copy()


# save LLM 1 output to disk along with prompt text
if not os.path.isfile(OUTPUT_LLM1_FILEPATH):

    print(f"Saving prompt and LLM response {OUTPUT_LLM1_FILEPATH.stem} [.txt, .csv] to {OUTPUT_LLM1_FILEPATH.parent} ...")
    with open(OUTPUT_PROMPT_FILEPATH, "w") as f:
        f.write(
            template.render(context=context, question=question_1)
        )
    df_responses_all.to_csv(OUTPUT_LLM1_FILEPATH, index=False)
else:
    print(f"Output file {Path(OUTPUT_LLM1_FILEPATH).stem} already exists. Skip saving to avoid overwriting ...")


    # # check if file exists already
    # if os.path.exists(OUTPUT_LMM1_FILEPATH):
    #     print(f"File {OUTPUT_LMM1_FILEPATH.name} already exists. Not saving to disk.")
    #     pass
    # else:
    #     print(f"Saving LLM 1 output to {OUTPUT_LMM1_FILEPATH}")
    #     df_responses_all.to_csv(OUTPUT_LMM1_FILEPATH, index=False)


print(
    f"CI_TYPE \n LLM responses:\n {df_responses.infrastructure_type.unique()}, \n\n NER pairs:\n {df_ci_geo.ci_entity.unique()}"
)

Saving prompt and LLM response llm_1_test_eval to ../../data/llm_outputs ...

## Evaluation - only manually

### Manual comparison CI_location_table vs LLm response

#### chunk 5
In Germany, road and railway infrastructure was severely damaged as documented exemplarily in Fig. 1. Cost estimates reach up to EURO 2 billion Euro (MDR, 2021). More than 130 km of motorways were closed directly after the event, of which 50 km were still closed two months later, with an estimated repair cost of EUR 100 million (Hauser, 2021). Of the 112 bridges in the ﬂooded 40 km of the Ahr valley (Rhineland-Palatinate), 62 bridges were destroyed, 13 were severely damaged and only 35 were in operation a month after the ﬂood event (MDR, 2021). Over 74 km of roads, paths and bridges in the Ahr valley have been (critically) damaged. In some cases, repairs are expected to take months to years (Zeit Online, 2021). For example, major freeway sections, including parts of the A1 motorway, were closed until early 2022 (24Rhein, 2022). In addition, about 50 000 cars were damaged, causing insurance claims of some EUR 450 million (ADAC, 2021). The German railway provider Deutsche Bahn expects asset damages of around EUR 1.3 billion. Among other things, 180 level crossings, almost 40 signal'

In [ ]:
doc[5].page_content

In [ ]:
df_ci_geo[df_ci_geo["chunk_id"] == 5]

In [ ]:
df_responses[df_responses["chunk_id"] == 5]

In [ ]:
print(
    f"CI_TYPE \n LLM responses:\n {df_responses.infrastructure_type.unique()}, \n\n NER pairs:\n {df_ci_geo.ci_entity.unique()}"
)

In [ ]:
print(
    f"LOCATION:\n LLm responses:\n {df_responses.location.unique()}, \n\n NER pairs:\n {df_ci_geo.geo_entity.unique()}"
)

### chunk 13 +14
'We found no information regarding direct impact on solid-waste facilities as a result of the ﬂood event. However, there is a large pressure on the solid-waste sector to clean the affected areas; 1 month after the event, we observed dozens of large temporary waste ﬁlls and frequent incidences of oil pollution in Rhineland-Palatinate during a ﬁeld visit. In the Ahrweiler district alone, the ﬂood caused as much solid waste as normally would be collected over 30 years. In Belgium, the amount of solid waste is estimated around 160 000 t, stored at several places, such as the abandoned highway track A601. This highway has been used for approximately 9 months as a temporary storage for debris (Couplez, 2022). In the Netherlands, there have been primarily problems with waste deposits along the river banks, which is mostly the solid waste transported by the river from further upstream. Thousands of tonnes of tree debris (logs and\nNat. Hazards Earth Syst. Sci., 22, 3831–3838, 2022\nE. E. Koks et al.: Flood impacts to infrastructure'


'of running water and electricity (Ärzte Zeitung, 2021). After 1.5 months, medical care was guaranteed again in the most affected regions in Rhineland-Palatinate (Hochwasser Ahr, 2021c). In the state of North Rhine-Westphalia, approximately 68 hospitals have been affected, of which several have been affected severely and will take at least 1.5 years to be rebuilt (Fig. 2). Direct damages are estimated to be at least EUR 100 million to repair all medical facilities (Korzilius, 2021). In the town of Eschweiler (Germany), for example, the basement of the hospital was ﬂooded, as well as the outbuildings and the entire outdoor area. The power supply collapsed, the entire building technology was destroyed and some 300 patients had to be evacuated by helicopter. Property damage is expected to be around EUR 50 million. Within 3.5 weeks, the hospital was partly operational, and within 3 months, all hospital operations continued normally (SAH Eschweiler, 2021). The Mutterhaus Ehrang hospital in Trier (Germany) is now permanently closed as the hospital is too severely damaged to rebuild. Furthermore, in the region of Rhineland-Palatinate (Germany), 19'

In [ ]:
doc[14].page_content

'of running water and electricity (Ärzte Zeitung, 2021). After 1.5 months, medical care was guaranteed again in the most affected regions in Rhineland-Palatinate (Hochwasser Ahr, 2021c). In the state of North Rhine-Westphalia, approximately 68 hospitals have been affected, of which several have been affected severely and will take at least 1.5 years to be rebuilt (Fig. 2). Direct damages are estimated to be at least EUR 100 million to repair all medical facilities (Korzilius, 2021). In the town of Eschweiler (Germany), for example, the basement of the hospital was ﬂooded, as well as the outbuildings and the entire outdoor area. The power supply collapsed, the entire building technology was destroyed and some 300 patients had to be evacuated by helicopter. Property damage is expected to be around EUR 50 million. Within 3.5 weeks, the hospital was partly operational, and within 3 months, all hospital operations continued normally (SAH Eschweiler, 2021). The Mutterhaus Ehrang hospital in Trier (Germany) is now permanently closed as the hospital is too severely damaged to rebuild. Furthermore, in the region of Rhineland-Palatinate (Germany), 19'

In [ ]:
df_ci_geo[df_ci_geo["chunk_id"].isin([13, 14])]

,chunk_id,ci_entity,ci_entity_label,geo_entity,geo_entity_label,token_distance
53,13,waste facilities,CI_TYPE,Rhineland-Palatinate,GPE,3
54,13,solid waste,CI_TYPE,Ahrweiler,LOC,1
55,13,solid waste,CI_TYPE,Belgium,GPE,1
56,13,highway,CI_TYPE,Belgium,GPE,3
57,13,A601,FAC,Belgium,GPE,4
58,13,highway,CI_TYPE,Netherlands,GPE,4
59,13,solid waste,CI_TYPE,Netherlands,GPE,1
60,14,hospitals,CI_TYPE,North Rhine-Westphalia,GPE,2
61,14,hospital,CI_TYPE,Germany,GPE,1
62,14,hospital,CI_TYPE,Germany,GPE,5
63,14,hospital,CI_TYPE,Trier,GPE,5
64,14,The Mutterhaus Ehrang,FAC,Trier,GPE,2
65,14,hospital,CI_TYPE,Trier,GPE,1
66,14,hospital,CI_TYPE,Germany,GPE,1

In [ ]:
df_responses[df_responses["chunk_id"].isin([13, 14])]

,chunk_id,infrastructure_type,damage,economic_impact,location,time,duration
31,13,waste facilities,dozens of large temporary waste fills and frequent incidences of oil pollution,as much solid waste as normally would be collected over 30 years,Rhineland-Palatinate,1 month after the event,approximately 30 years
32,13,highway,used for approximately 9 months as a temporary storage for debris,thousands of tonnes of tree debris,Belgium,9 months after the event,approximately 30 years
33,13,solid waste,caused as much solid waste as normally would be collected over 30 years,estimated around 160 000 t,Ahrweiler district,1 month after the event,approximately 30 years
34,13,river banks,primarily problems with waste deposits,thousands of tonnes of tree debris,Netherlands,after the event,approximately 30 years
35,14,hospitals,"approximately 68 hospitals have been affected, of which several have been affected severely and will take at least 1.5 years to be rebuilt",direct damages are estimated to be at least EUR 100 million to repair all medical facilities,North Rhine-Westphalia,after 1.5 months,at least 1.5 years
36,14,hospitals,"the basement of the hospital was flooded, as well as the outbuildings and the entire outdoor area",property damage is expected to be around EUR 50 million,Eschweiler (Germany),within 3.5 weeks,within 3 months
37,14,hospital,The Mutterhaus Ehrang hospital in Trier (Germany) is now permanently closed as the hospital is too severely damaged to rebuild,"furthermore, in the region of Rhineland-Palatinate (Germany), 19'",Trier,now,

In [ ]:
print(
    f"CI_TYPE \n LLM responses:\n {df_responses.infrastructure_type.unique()}, \n\n NER pairs:\n {df_ci_geo.ci_entity.unique()}"
)

In [ ]:
print(
    f"LOCATION:\n LLm responses:\n {df_responses.location.unique()}, \n\n NER pairs:\n {df_ci_geo.geo_entity.unique()}"
)

## Test alternative approaches for entity linking / relation extraction

In [ ]:
import torch
import gc

print(torch.cuda.memory_summary(device=None, abbreviated=False))
# # empyty CUDA cache
gc.collect()

torch.cuda.empty_cache()
# print(torch.cuda.memory_summary(device=None, abbreviated=False))